#SG
substitutions:
  _MY_BLOG_IMAGE_NAME: cloud-wp
  # _CODE_BLOG_IMAGE_NAME: code-blog
  # _STATIC_FILES_IMAGE_NAME: static-files
steps:
  # my blog
  - id: cloud-wp-cache-image
    name: gcr.io/cloud-builders/docker
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        docker pull asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$BRANCH_NAME || exit 0
    waitFor: ["-"]
  - id: cloud-wp-build-image
    name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$BRANCH_NAME",
        "-t",
        "asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$SHORT_SHA",
        "docker/cloud-wp/",
      ]
    waitFor: ["cloud-wp-cache-image"]

# https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts
images:
  - asia.gcr.io/$PROJECT_ID/$_MY_BLOG_IMAGE_NAME:$SHORT_SHA
