apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloud-wp-wp-cron
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: cloud-wp-wp-config
              configMap:
                name: cloud-wp-wp-config
          containers:
            - name: wp-cron
              image: gcr.io/dotted-byway-282020/cloud-wp:stage1
              command: ["/usr/local/bin/php"]
              args:
                - /usr/src/wordpress/wp-cron.php
              volumeMounts:
                - name: my-blog-wp-config
                  mountPath: /usr/src/wordpress/wp-config.php
                  subPath: wp-config.php
                  readOnly: true
              resources:
                requests:
                  cpu: 10m
                  memory: 100Mi
                limits:
                  memory: 100Mi
          restartPolicy: OnFailure
